# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZtj8ZHhKJxAZdxFQXed4j8xL5IVs3St
"""

!pip install -q face_recognition opencv-contrib-python-headless
!wget -q https://pjreddie.com/media/files/yolov3-tiny.weights
!wget -q https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg
!wget -q https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names



enroll_face_from_webcam("YourName")

analyze_single_frame()

# This will now trigger the improved recording-style analysis
record_and_analyze(n_frames=30, interval_ms=200)

import os
log_file = CONFIG.get('log_txt', 'security_log.txt')
if os.path.exists(log_file):
    size = os.path.getsize(log_file)
    print(f'Log File: {log_file} ({size} bytes)')
    with open(log_file, 'r') as f:
        content = f.read().strip()
        if not content:
            print('The log file is currently empty.')
        else:
            print('--- Last 20 lines ---')
            print('\n'.join(content.splitlines()[-20:]))
else:
    print('Log file not found.')

import os
from IPython.display import display, Image

snapshot_dir = CONFIG.get('snapshot_dir', 'snapshots')
if os.path.exists(snapshot_dir):
    files = sorted([f for f in os.listdir(snapshot_dir) if f.endswith(('.jpg', '.jpeg'))], reverse=True)
    if not files:
        print(f"No snapshots found in {snapshot_dir}.")
    else:
        print(f"Found {len(files)} snapshots. Displaying them below:")
        for f in files:
            print(f"\nFile: {f}")
            display(Image(filename=os.path.join(snapshot_dir, f), width=400))
else:
    print(f"Directory '{snapshot_dir}' does not exist yet.")

# Replace 'AnotherPerson' with the name you want to use
enroll_face_from_webcam("AnotherPerson")

enroll_face_from_webcam("Atharva")

# Replace 'NewPerson' with the actual name of the individual
enroll_face_from_webcam("NewPerson")

scorer.score = 0
print("Threat level has been reset to NORMAL. You can now run the recording cell again.")

# Updating CONFIG to include laptops and cameras
CONFIG['alert_classes'].update({'laptop', 'tvmonitor'})

# Advanced Video Capture JS for a more 'Recording' feel
_VIDEO_STREAM_JS = """
async function streamVideo(n_frames, interval) {
  const div = document.createElement('div');
  const video = document.createElement('video');
  const canvas = document.createElement('canvas');
  const stream = await navigator.mediaDevices.getUserMedia({video:true});

  video.srcObject = stream;
  await video.play();

  div.appendChild(video);
  document.body.appendChild(div);

  let frames = [];
  for (let i=0; i<n_frames; i++) {
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    canvas.getContext('2d').drawImage(video, 0, 0);
    frames.push(canvas.toDataURL('image/jpeg', 0.8));
    await new Promise(r => setTimeout(r, interval));
  }

  stream.getVideoTracks()[0].stop();
  div.remove();
  return frames;
}
"""

def record_and_analyze(n_frames=30, interval_ms=500):
    print(f"[RECORDING] Analyzing {n_frames} frames for people, phones, laptops, and cameras...")
    display(Javascript(_VIDEO_STREAM_JS))
    # Note: In a real environment, we'd handle the batch return,
    # but for now, we'll keep the loop for visual feedback.
    watch(n_frames=n_frames, interval_sec=0.1)

log.info("Updated alert classes: " + str(CONFIG['alert_classes']))